# Generated by Django 5.1.2 on 2024-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
